name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master  # Change to your default branch if different

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: ${{ github.event.repository.name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Build the Flutter web app
      - name: Build Flutter web
        run: flutter build web

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BELUGANG_VERIFICATION_WEB_APP }}
          projectId: belugang-verification-web-app
